kv_namespaces = [
  { binding = "KV", id = "998f9a4d431847f694da0d2d9cd027be", preview_id = "9b1665fea67b446495de66880ffa9a6a" }
]

r2_buckets  = [
  { binding = "BUCKET", bucket_name = "scoutsheirbrug", preview_bucket_name = "scoutsheirbrug-preview" }
]
